<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class StickingPointsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('sticking_points')->delete();
        
        \DB::table('sticking_points')->insert(array (
            0 => 
            array (
                'id' => 1,
                'genre_code' => 1,
                'stickingpoint_cat' => 1,
                'name' => 'ローコスト住宅',
                'supplement_text' => '1,000万円台／坪単価20万から40万円台',
                'select_item' => 'ローコスト住宅
1,000万円台／坪単価20万から40万円台',
                'breadcrumb' => 'ローコスト住宅',
            'title_h1' => 'ローコスト住宅(1000万円台)',
                'title_h2' => 'ローコスト住宅(1000万円台)',
                'url_text' => '',
                'view_type' => 2,
                'is_sup' => 1,
                'created_at' => '2020-12-22 22:17:59',
                'updated_at' => '2020-12-31 02:13:52',
            ),
            1 => 
            array (
                'id' => 2,
                'genre_code' => 1,
                'stickingpoint_cat' => 1,
                'name' => 'ハイグレード住宅',
                'supplement_text' => '3,000万円以上／坪単価100万円以上',
                'select_item' => 'ハイグレード住宅
3,000万円以上／坪単価100万円以上',
                'breadcrumb' => 'ハイグレード住宅',
            'title_h1' => 'ハイグレード住宅(3000万円台)',
            'title_h2' => 'ハイグレード住宅(3000万円台)',
                'url_text' => '',
                'view_type' => 2,
                'is_sup' => 1,
                'created_at' => '2020-12-22 22:19:20',
                'updated_at' => '2020-12-31 02:13:52',
            ),
            2 => 
            array (
                'id' => 3,
                'genre_code' => 1,
                'stickingpoint_cat' => 2,
                'name' => '和モダン',
                'supplement_text' => '',
                'select_item' => '和モダン',
                'breadcrumb' => '和モダン',
                'title_h1' => '和モダン住宅',
                'title_h2' => '和モダン住宅',
                'url_text' => '',
                'view_type' => 2,
                'is_sup' => 0,
                'created_at' => '2020-12-22 22:20:25',
                'updated_at' => '2020-12-31 02:13:52',
            ),
            3 => 
            array (
                'id' => 4,
                'genre_code' => 1,
                'stickingpoint_cat' => 2,
                'name' => '輸入住宅',
                'supplement_text' => '',
                'select_item' => '輸入住宅',
                'breadcrumb' => '輸入住宅',
                'title_h1' => '輸入住宅',
                'title_h2' => '輸入住宅',
                'url_text' => '',
                'view_type' => 2,
                'is_sup' => 0,
                'created_at' => '2020-12-22 22:20:25',
                'updated_at' => '2020-12-31 02:13:52',
            ),
            4 => 
            array (
                'id' => 5,
                'genre_code' => 1,
                'stickingpoint_cat' => 2,
                'name' => '自然素材・無垢素材',
                'supplement_text' => '',
                'select_item' => '自然素材・
無垢素材',
                'breadcrumb' => '自然素材・無垢素材',
                'title_h1' => '自然素材・無垢素材',
                'title_h2' => '自然素材・無垢素材',
                'url_text' => '',
                'view_type' => 2,
                'is_sup' => 0,
                'created_at' => '2020-12-22 22:20:25',
                'updated_at' => '2020-12-31 02:13:52',
            ),
            5 => 
            array (
                'id' => 6,
                'genre_code' => 1,
                'stickingpoint_cat' => 2,
                'name' => 'カッコイイ',
                'supplement_text' => '',
                'select_item' => 'カッコイイ',
                'breadcrumb' => 'カッコイイ',
                'title_h1' => 'カッコイイ家',
                'title_h2' => 'カッコイイ家',
                'url_text' => '',
                'view_type' => 2,
                'is_sup' => 0,
                'created_at' => '2020-12-22 22:20:25',
                'updated_at' => '2020-12-31 02:13:52',
            ),
            6 => 
            array (
                'id' => 7,
                'genre_code' => 1,
                'stickingpoint_cat' => 2,
                'name' => 'おしゃれ',
                'supplement_text' => '',
                'select_item' => 'おしゃれ',
                'breadcrumb' => 'おしゃれ',
                'title_h1' => 'おしゃれな家',
                'title_h2' => 'おしゃれな家',
                'url_text' => '',
                'view_type' => 2,
                'is_sup' => 0,
                'created_at' => '2020-12-22 22:23:17',
                'updated_at' => '2020-12-31 02:13:52',
            ),
            7 => 
            array (
                'id' => 8,
                'genre_code' => 1,
                'stickingpoint_cat' => 2,
                'name' => '可愛い',
                'supplement_text' => '',
                'select_item' => '可愛い',
                'breadcrumb' => '可愛い',
                'title_h1' => '可愛い家',
                'title_h2' => '可愛い家',
                'url_text' => '',
                'view_type' => 2,
                'is_sup' => 0,
                'created_at' => '2020-12-22 22:23:17',
                'updated_at' => '2020-12-31 02:13:52',
            ),
            8 => 
            array (
                'id' => 9,
                'genre_code' => 2,
                'stickingpoint_cat' => 3,
                'name' => '第一種住居地域',
                'supplement_text' => '',
                'select_item' => '第一種住居地域',
                'breadcrumb' => '第一種住居地域',
                'title_h1' => '第一種住居地域',
                'title_h2' => '第一種住居地域',
                'url_text' => '',
                'view_type' => 1,
                'is_sup' => 0,
                'created_at' => NULL,
                'updated_at' => '2020-12-31 02:13:52',
            ),
            9 => 
            array (
                'id' => 10,
                'genre_code' => 2,
                'stickingpoint_cat' => 3,
                'name' => '第二種住居地域',
                'supplement_text' => '',
                'select_item' => '第二種住居地域',
                'breadcrumb' => '第二種住居地域',
                'title_h1' => '第二種住居地域',
                'title_h2' => '第二種住居地域',
                'url_text' => '',
                'view_type' => 1,
                'is_sup' => 0,
                'created_at' => NULL,
                'updated_at' => '2020-12-31 02:13:52',
            ),
            10 => 
            array (
                'id' => 11,
                'genre_code' => 3,
                'stickingpoint_cat' => 4,
                'name' => '一戸建て',
                'supplement_text' => '',
                'select_item' => '一戸建て',
                'breadcrumb' => '一戸建て',
                'title_h1' => '一戸建て',
                'title_h2' => '一戸建て',
                'url_text' => '',
                'view_type' => 2,
                'is_sup' => 0,
                'created_at' => NULL,
                'updated_at' => '2020-12-31 02:13:52',
            ),
            11 => 
            array (
                'id' => 12,
                'genre_code' => 3,
                'stickingpoint_cat' => 4,
                'name' => 'マンション',
                'supplement_text' => '',
                'select_item' => 'マンション',
                'breadcrumb' => 'マンション',
                'title_h1' => 'マンション',
                'title_h2' => 'マンション',
                'url_text' => '',
                'view_type' => 2,
                'is_sup' => 0,
                'created_at' => NULL,
                'updated_at' => '2020-12-31 02:13:52',
            ),
            12 => 
            array (
                'id' => 13,
                'genre_code' => 3,
                'stickingpoint_cat' => 4,
                'name' => 'オフィス等・その他',
                'supplement_text' => '',
                'select_item' => 'オフィス等
・その他',
                'breadcrumb' => 'オフィス等・その他',
                'title_h1' => 'オフィス等・その他',
                'title_h2' => 'オフィス等・その他',
                'url_text' => '',
                'view_type' => 2,
                'is_sup' => 0,
                'created_at' => NULL,
                'updated_at' => '2020-12-31 02:13:52',
            ),
            13 => 
            array (
                'id' => 14,
                'genre_code' => 3,
                'stickingpoint_cat' => 5,
                'name' => '水まわり',
                'supplement_text' => 'キッチン・システムキッチン  |  浴室・バス・ユニットバス  |  洗面所・脱衣所  |  トイレ',
                'select_item' => '水まわり
キッチン・システムキッチン  |  浴室・バス・ユニットバス  |  洗面所・脱衣所  |  トイレ',
                'breadcrumb' => '水まわり',
                'title_h1' => '水まわり（キッチン・浴室・トイレなど）',
                'title_h2' => '水まわり（キッチン・浴室・トイレなど）',
                'url_text' => '',
                'view_type' => 1,
                'is_sup' => 1,
                'created_at' => '2020-12-22 22:28:22',
                'updated_at' => '2020-12-31 02:13:52',
            ),
            14 => 
            array (
                'id' => 15,
                'genre_code' => 3,
                'stickingpoint_cat' => 5,
                'name' => '屋内',
                'supplement_text' => 'リビング・ダイニング  |  収納  |  寝室  |  和室  |  子ども部屋  |  書斎  |  ロフト  |  洋室  |  階段  |  廊下  |  玄関',
                'select_item' => '屋内
リビング・ダイニング  |  収納  |  寝室  |  和室  |  子ども部屋  |  書斎  |  ロフト  |  洋室  |  階段  |  廊下  |  玄関',
                'breadcrumb' => '屋内',
                'title_h1' => '屋内（リビング・ダイニング・子ども部屋など） ',
                'title_h2' => '屋内（リビング・ダイニング・子ども部屋など）',
                'url_text' => '',
                'view_type' => 1,
                'is_sup' => 1,
                'created_at' => NULL,
                'updated_at' => '2020-12-31 02:13:52',
            ),
            15 => 
            array (
                'id' => 16,
                'genre_code' => 3,
                'stickingpoint_cat' => 5,
                'name' => '屋外',
                'supplement_text' => '外壁外装・屋根  |  エクステリア・バルコニー・庭',
                'select_item' => '屋外
外壁外装・屋根  |  エクステリア・バルコニー・庭',
                'breadcrumb' => '屋外',
                'title_h1' => '屋外（外壁外装・屋根・庭など）',
                'title_h2' => '屋外（外壁外装・屋根・庭など）',
                'url_text' => '',
                'view_type' => 1,
                'is_sup' => 1,
                'created_at' => NULL,
                'updated_at' => '2020-12-31 02:13:52',
            ),
            16 => 
            array (
                'id' => 17,
                'genre_code' => 4,
                'stickingpoint_cat' => 6,
                'name' => '区分マンション',
                'supplement_text' => '',
                'select_item' => '区分マンション',
                'breadcrumb' => '区分マンション',
                'title_h1' => '区分マンション投資',
                'title_h2' => '区分マンション投資',
                'url_text' => '',
                'view_type' => 1,
                'is_sup' => 0,
                'created_at' => NULL,
                'updated_at' => '2020-12-31 02:13:52',
            ),
            17 => 
            array (
                'id' => 18,
                'genre_code' => 4,
                'stickingpoint_cat' => 6,
                'name' => '売りアパート',
                'supplement_text' => '',
                'select_item' => '売りアパート',
                'breadcrumb' => '売りアパート',
                'title_h1' => '売りアパート投資',
                'title_h2' => '売りアパート投資',
                'url_text' => '',
                'view_type' => 1,
                'is_sup' => 0,
                'created_at' => NULL,
                'updated_at' => '2020-12-31 02:13:52',
            ),
            18 => 
            array (
                'id' => 19,
                'genre_code' => 4,
                'stickingpoint_cat' => 6,
                'name' => '一棟マンション・アパート',
                'supplement_text' => '',
                'select_item' => '一棟マンション・アパート',
                'breadcrumb' => '一棟マンション・アパート',
                'title_h1' => '一棟マンション・アパート投資',
                'title_h2' => '一棟マンション・アパート投資',
                'url_text' => '',
                'view_type' => 1,
                'is_sup' => 0,
                'created_at' => NULL,
                'updated_at' => '2020-12-31 02:13:52',
            ),
            19 => 
            array (
                'id' => 20,
                'genre_code' => 4,
                'stickingpoint_cat' => 6,
                'name' => '戸建て',
                'supplement_text' => '',
                'select_item' => '戸建て',
                'breadcrumb' => '戸建て',
                'title_h1' => '戸建て投資',
                'title_h2' => '戸建て投資',
                'url_text' => '',
                'view_type' => 1,
                'is_sup' => 0,
                'created_at' => NULL,
                'updated_at' => '2020-12-31 02:13:52',
            ),
            20 => 
            array (
                'id' => 21,
                'genre_code' => 4,
                'stickingpoint_cat' => 6,
                'name' => '区分マンション',
                'supplement_text' => '',
                'select_item' => '区分マンション',
                'breadcrumb' => '区分マンション',
                'title_h1' => '区分マンション投資',
                'title_h2' => '区分マンション投資',
                'url_text' => '',
                'view_type' => 1,
                'is_sup' => 0,
                'created_at' => NULL,
                'updated_at' => '2020-12-31 02:13:52',
            ),
        ));
        
        
    }
}